"""
Write a portable SoapySDRConfig.cmake for the GPredict-Improved Windows CI.

Usage:
    python scripts/write_soapy_cmake_config.py --sdk-dir soapy-win64/sdk

Generates <sdk-dir>/lib/cmake/SoapySDR/SoapySDRConfig.cmake that points
find_package(SoapySDR) at the headers and SoapySDR.lib extracted from the
pinned conda package.  The conda-supplied cmake config files have absolute
paths baked in at conda build time, so they are unusable after extraction.
This script writes a portable config using paths relative to the sdk-dir
argument (resolved to an absolute path at write time).
"""

import argparse
import sys
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sdk-dir", required=True, help="Path to soapy-win64/sdk/")
    args = parser.parse_args()

    sdk = Path(args.sdk_dir).resolve()
    include_dir = sdk / "include"
    lib_dir = sdk / "lib"

    if not include_dir.is_dir():
        print(f"ERROR: include dir not found: {include_dir}", file=sys.stderr)
        return 1

    soapy_lib = next(lib_dir.rglob("SoapySDR.lib"), None)
    if soapy_lib is None:
        print(f"ERROR: SoapySDR.lib not found under {lib_dir}", file=sys.stderr)
        return 1

    cmake_dir = lib_dir / "cmake" / "SoapySDR"
    cmake_dir.mkdir(parents=True, exist_ok=True)

    inc = include_dir.as_posix()
    lib = soapy_lib.as_posix()

    config = (
        "# Auto-generated by GPredict-Improved CI — do not edit.\n"
        "# Points find_package(SoapySDR) at the SDK extracted from the pinned\n"
        "# soapysdr-0.8.1-py311haef1a59_6.conda so that rtlsdrSupport.dll embeds\n"
        "# the same SOAPY_SDR_ABI_VERSION as the bundled SoapySDR.dll.\n"
        "set(SoapySDR_FOUND TRUE)\n"
        'set(SoapySDR_VERSION "0.8.1")\n'
        'set(SOAPY_SDR_ABI_VERSION "0.8")\n'
        f'set(SOAPY_SDR_INCLUDE_DIR "{inc}")\n'
        f'set(SoapySDR_INCLUDE_DIRS "{inc}")\n'
        f'set(SoapySDR_LIBRARIES "{lib}")\n'
        f'set(SoapySDR_LIBRARY_DIRS "{lib_dir.as_posix()}")\n'
        "if(NOT TARGET SoapySDR::SoapySDR)\n"
        "  add_library(SoapySDR::SoapySDR IMPORTED SHARED)\n"
        "  set_target_properties(SoapySDR::SoapySDR PROPERTIES\n"
        f'    IMPORTED_IMPLIB "{lib}"\n'
        f'    INTERFACE_INCLUDE_DIRECTORIES "{inc}"\n'
        "  )\n"
        "endif()\n"
    )

    out = cmake_dir / "SoapySDRConfig.cmake"
    out.write_text(config, encoding="utf-8")
    print(f"Wrote {out}")
    print(f"  include: {inc}")
    print(f"  lib:     {lib}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
